#!/bin/sh

#before the analysis, please download the data from GISAID 
#GISAID accessionIds sets
#EPI_SET_20220531ye: 927,436 nucleotide and 927,088 protein sequences corresponding to 115,520 IAV whole genomes
#EPI_SET_250116bq: recently emerging human H3N8 and highly pathogenic avian influenza A H5 viruses

#Part 1. data filtering and alignment
#8 CDSs, PB2, PB1, PA, HA, NP, NA, M1, NS1, using PB2 as an example
cd Scripts/block_alignment
mono data_filtering PB2_raw_aafile.fasta PB2_raw_ntfile.fasta metafile.csv ./filter
mono seq_grouping.exe #compile from seq_grouping.cs
./runMAFFT.sh 
mono block_alignment/extract_consensus.exe #compile from extract_consensus.cs
#generate the UPGMA guide tree with the consensus sequences at https://mafft.cbrc.jp/alignment/server/index.html
./runClustalO.sh
./runPal2Nal.sh

#Part 2. phylogenetic tree construction and lineage clustering
cd Scripts/phylogenetic
./runFastTree.sh
python reRootByMidpoint.py PB2_nt_pal2nal.fasttree
python collapseTree.py PB2_nt_pal2nal.fasttree_midpoint 0.00000001
python addInnodeName2Tree.py PB2_nt_pal2nal.fasttree_midpoint_collapsed
./runPastML.sh 
#The 12 mammalian persistent lineages for human, swine, canine and equine IAVs were defined 
#based on the groupings in the collapsed trees (in phylogenetic/PastML) and metadata (subtypes, geographic regions and isolation time)
#More details in Supplementary Table 14 and seqname_lineage.txt
#Fig. 1 is generated by FigTree using trees saved in /Trees

#Part 3. GC content and GC dinucleotide frequencies
cd Scripts/genomic_features
#computeFeature.py is a combined script to calculate GC/GC12/GC3 contents, CpG/GpC/GpG/CpC dinucleotide frequencies and O/E ratios
#please edit the input files to run it
#Here shows an example for mink H5 IAVs to demonstrate the example present at https://iav-transmission.org/
#The full features for developing the SVM model is saved at genomic_features/all_features_seqname_lineage_year.tsv
#Genomic GC content and GC dinucleotide frequencies are saved at /GC_content and /Dinucleotide
python computeFeature.py
gemonic_gc_plot.m #plot for Fig. 2a
#Fig. 2b is generated by prism (a GUI tool) using data from Supplementary Table 1
barplot_regression_slope.r #plot for Fig. 2c (Extended Data Table 1 and Supplementary Table 2), Fig. 3a (Supplementary Table 2) and Fig. 3d (Supplementary Table 5)
#Fig. 2b is generated by prism using data from Supplementary Table 1
#Fig. 3b is generated by prism using data from Supplementary Table 4 
GC_subtype_avianFamily_plot.r #plot for Fig. 4a and Extended Data Fig. 3 using data in genomic_feature/GC_subtype_avianFamily_data folder
#Fig. 5d is generated by prism using data saved in recentH5_HuH3N8_genomic_gc_content.csv
violin_avian_HA_NA.r generates Supplementary Fig. 11

#Part 4. codon usage bias
cd Scripts/codon_bias
#results in /CAI
compute_cai.ipynb
cai_plot.m #plot for Extended Data Fig. 1

#Part 5. RNA secondary structure
cd Scripts/RNA_secondary_structure
#results in /CAI
./runRNAfold.sh
RNAfold_script.cs #is a combined script to extract the free energy of RNA folding from the outputs of ViennaRNA-2.6.4/RNAfold,
# and map to GC/GC12/GC3 contents.
# Results are saved at /MFE
mfe_gc_correlation.m #calculate the correlation coefficients saved at correlation coefficient.xlsx
#Extended Data Fig. 2 is generated by prism using data in correlation coefficient.xlsx

#Part 6. causal inference
cd Scripts/causal_discovery
causal_discovery.r
#Fig. 3c is generated by prism based on the results saved in causal_discovery.xlsx

#Part 7. linear discriminant analysis
cd LDA
python LDA_plot_2d_all.py:  linear discriminant analysis to generate Fig. 4c, Fig. 5a,c, Extended Data Fig. 4 and Supplementary Fig. 14a

#Part 8. smoothed density estimates
cd smoothed_density_estimate
density_annotated_sporadic_aivan.r: generate Fig. 4b and Supplementary Fig. 4

#Part 9. SVM
cd /Scripts/SVM
get_train_test_data_libsvmformat.cs: generate the training and testing datasets for main SVM, and other benchmarks
run_Train_Predict_2weights_kernal_C.sh: traverse different model parameters
SummarySVMTrain.cs: summarize the output logs from the model traversal and select the bese model 
Fig. 4d and Fig. 4e are generated by prism based on the results saved in persistent_svm_result/svm_bestmodel_main_individual.xlsx
svm_plot_predict.m: generate Fig. 5b
Supplementary Fig. 7 is generated by prism based on the results saved in early2later/svm_bestmodel_early2later.csv and later2early/svm_bestmodel_later2early.csv
Supplementary Fig. 8 is generated by prism based on the results saved in 66_10To2_lineage/svm_bestmodel_66_10To2_lineage.csv
Supplementary Fig. 9 is generated by prism based on the results saved in noHu3Hu4_lineage/svm_bestmodel_noHu3Hu4.csv
Supplementary Fig. 10 is generated by prism based on the results saved in 12_11To1_lineage/svm_bestmodel_12_11To1_lineage.csv
Supplementary Fig. 12 is generated by prism based on the results saved in svm_result/svm_bestmodel_main_individual.xlsx
Supplementary Fig. 13 is generated by prism based on the results saved in svm_result/svm_bestmodel_main_individual.xlsx

#Part 10. Random Forest
cd RandomForest
random_forest_train_predict.ipynb #genetate data for Supplementary Fig. 14


#Part 11. Mechanistic insights
Extended Data Fig. 5 is generated by prism using data in Supplementary Table 10.

#Part 12. phylogeographics analysis
cd phylogeographics
phylogeographics_plot.R : generate Extended Data Fig. 6c.

#Part 13. Tree annotation
cd tree annotation
tree_annotation.r: generate Extended Data Fig. 6b and Supplementary Fig. 16-23.

#Part 14. Point mutation
point_mutation.r: generate Extended Data Fig. 7

#Part 15. Duration of IAV circulation in mammals
Supplementary Fig. 2 is generated by prism using data in Supplementary Table 6.