#!/bin/sh

#before the analysis, please download the data from GISAID 
#GISAID accessionIds sets
#EPI_SET_20220531ye: 927,436 nucleotide and 927,088 protein sequences corresponding to 115,520 IAV whole genomes
#EPI_SET_250116bq: recently emerging human H3N8 and highly pathogenic avian influenza A H5 viruses

#Part 1. data filtering and alignment
#8 CDSs, PB2, PB1, PA, HA, NP, NA, M1, NS1, using PB2 as an example
cd block_alignment
mono data_filtering.exe PB2_raw_aafile.fasta PB2_raw_ntfile.fasta metafile.csv ./filter
mono seq_grouping.exe #compile from seq_grouping.cs
./runMAFFT.sh 
mono extract_consensus.exe #compile from extract_consensus.cs
#to complie a C# program
#>>conda install conda-forge::mono
#>>mcs extract_consensus.cs
#generate the UPGMA guide tree with the consensus sequences at https://mafft.cbrc.jp/alignment/server/index.html
./runClustalO.sh
./runPal2Nal.sh

#Part 2. phylogenetic tree construction and lineage clustering
cd phylogenetic
./runFastTree.sh
python reRootByMidpoint.py PB2_nt_pal2nal.fasttree
python collapseTree.py PB2_nt_pal2nal.fasttree_midpoint 0.00000001
python addInnodeName2Tree.py PB2_nt_pal2nal.fasttree_midpoint_collapsed
./runPastML.sh 
#The 12 mammalian persistent lineages for human, swine, canine and equine IAVs were defined 
#based on the groupings in the collapsed trees (in phylogenetic/PastML) and 
#metadata (subtypes, geographic regions and isolation time)
#More details in Supplementary Table 16 and seqname_lineage.txt
#Fig. 1 is generated by FigTree using trees saved in /IAV_GCContent/Trees

#Part 3. GC content and GC dinucleotide frequencies
cd genomic_features
#computeFeature.py is a combined script to calculate GC/GC12/GC3 contents, 
#CpG/GpC/GpG/CpC dinucleotide frequencies and O/E ratios
#PLEASE edit the input files to run it
#Here shows an example for mink H5 IAVs to demonstrate the example present at https://iav-transmission.org/
#The full features for developing the SVM model is saved at genomic_features/all_features_seqname_lineage_year.tsv
#Genomic GC content and GC dinucleotide frequencies are saved at /IAV_GCContent/GC_content and /IAV_GCContent/Dinucleotide
cd /IAV_GCContent/SVM_model
python computeFeature.py #features saved in /IAV_GCContent/SVM_model/demo_minkH5_cds/gc_content_dinucleotide_libsvm.txt
cd /IAV_GCContent/Scripts/genomic_features
matlab emonic_gc_plot.m #plot for Fig. 2a using data in /IAV_GCContent/GC_content
#Fig. 2b is generated by prism (a GUI tool) using data from Supplementary Table 2.
r barplot_regression_slope.r #plot for Fig. 2c (Supplementary Tables 1 and 3), Fig. 3a (Supplementary Table 5) and Fig. 3d (Supplementary Table 7)
#barplot_regression_slope.r is a combined script.
#Fig. 3b is generated by prism using data from  Supplementary Table 6.
GC_subtype_avianFamily_plot.r #plot for Fig. 4a and Extended Data Fig. 3 using data in genomic_feature/GC_subtype_avianFamily_data
#Fig. 5d is generated by prism using data saved in genomic_features/recentH5_HuH3N8_genomic_gc_content.csv
r violin_avian_HA_NA.r #generates Supplementary Fig. 11 using data in genomic_feature/GC_subtype_avianFamily_data

#Part 4. codon usage bias
cd codon_bias
compute_cai.ipynb #results have saved in /IAV_GCContent/CAI
cai_plot.m #plot for Extended Data Fig. 1

#Part 5. RNA secondary structure
cd RNA_secondary_structure
./runRNAfold.sh #run ViennaRNA-2.6.4/RNAfold to compute the free energy of RNA folding 
mono RNAfold_script.exe 
#RNAfold_script.cs is a combined script to extract the free energy of RNA folding 
#from the outputs of the tool ViennaRNA-2.6.4/RNAfold,
#and map to GC/GC12/GC3 contents.
#Results are saved at /IAV_GCContent/MFE
matlab mfe_gc_correlation.m #calculate the correlation coefficients saved in correlation coefficient.xlsx
#Extended Data Fig. 2 is generated by prism using data in correlation coefficient.xlsx

#Part 6. causal inference
cd causal_discovery
r causal_discovery.r #compute causal inference and save result in causal_discovery.xlsx
#Fig. 3c is generated by prism based on the results saved in causal_discovery.xlsx

#Part 7. linear discriminant analysis
cd LDA
unzip all_features_predict_lineage_year.zip #unzip to all_features_predict_lineage_year.csv
python LDA_plot_2d_all.py # linear discriminant analysis to generate Fig. 4c, Fig. 5a,c, Extended Data Fig. 4 and Supplementary Fig. 14a

#Part 8. smoothed density estimates
cd smoothed_density_estimate
r density_annotated_sporadic_aivan.r: generate Fig. 4b and Supplementary Fig. 4

#Part 9. SVM
cd /IAV_GCContent/SVM_model
#run the demo_minkH5_cds
./runDemo.sh
#train the main SVM model using features from 8 CDSs
./runLIBSVM.sh

cd /IAV_GCContent/Scripts/SVM
mono get_train_test_data_libsvmformat.exe
#get_train_test_data_libsvmformat.cs generates the training and testing datasets for main SVM, and other benchmarks
run_Train_Predict_2weights_kernal_C.sh 
#traverse different model parameters, save the output logs to validate_12_11To1_lineage_c_5fold_x.txt and result_12_11To1_lineage_c_5fold_x.txt
mono SummarySVMTrain.exe
#SummarySVMTrain.cs summarizes the output logs from the model traversal and select the best model 
#Fig. 4d and Fig. 4e are generated by prism based on the results saved in svm_result/svm_bestmodel_main_individual.xlsx
matlab svm_plot_predict.m # generate Fig. 5b
#Supplementary Fig. 7 is generated by prism based on the results saved in early2later/svm_bestmodel_early2later.csv and later2early/svm_bestmodel_later2early.csv
#Supplementary Fig. 8 is generated by prism based on the results saved in 66_10To2_lineage/svm_bestmodel_66_10To2_lineage.csv
#Supplementary Fig. 9 is generated by prism based on the results saved in noHu3Hu4_lineage/svm_bestmodel_noHu3Hu4.csv
#Supplementary Fig. 10 is generated by prism based on the results saved in 12_11To1_lineage/svm_bestmodel_12_11To1_lineage.csv
#Supplementary Fig. 12 is generated by prism based on the results saved in svm_result/svm_bestmodel_main_individual.xlsx
#Supplementary Fig. 13 is generated by prism based on the results saved in svm_result/svm_bestmodel_main_individual.xlsx

#Part 10. Random Forest
cd RandomForest
random_forest_train_predict.ipynb #genetate data for Supplementary Fig. 14

#Part 11. Mechanistic insights
#Extended Data Fig. 5 is generated by prism using data in Supplementary Table 12.

#Part 12. phylogeographics analysis
cd phylogeographics
r phylogeographics_plot.R #generate Fig. 6c.

#Part 13. Tree annotation
cd tree_annotation
r tree_annotation.r: generate Fig. 6b and Supplementary Fig. 16-23.

#Part 14. Point mutation
r point_mutation.r: generate Extended Data Fig. 6

#Part 15. Duration of IAV circulation in mammals
#Supplementary Fig. 2 is generated by prism using data in Supplementary Table 8.



